[package]
name = "clahe"
version = "0.2.0"
edition = "2021"

description = "CLAHE (Contrast Limited Adaptive Histogram Equalisation)"
authors = ["Yuki SUZUKI <y-suzuki@radiol.med.osaka-u.ac.jp>"]
repository = "https://github.com/ykszk/clahe"
license = "MIT"

[[bin]]
name = "clahe"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.50", features = ["derive"] }
env_logger = "0.11.8"
log = "0.4.28"
image = { version = "0.25.8", features = [
    "jpeg",
    "png",
], default-features = false }
ndarray = "0.16.1"
num-traits = "0.2.19"
ndarray-stats = "0.6.0"
coolor = "1.1.0"
thiserror = "2.0.17"

[dev-dependencies]
imageproc = "0.25.0"
pretty_assertions = "1.4.1"
ndarray-rand = "0.15.0"
criterion = { version = "0.7.0", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false
